/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class cafe_jframe extends javax.swing.JFrame {

    /**
     * Creates new form cafe_jframe
     */
    public cafe_jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cb3 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblchange = new javax.swing.JLabel();
        lbltot1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn3 = new javax.swing.JButton();
        txtpay = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btncalc = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnd = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnitems1 = new javax.swing.JButton();
        btnClearItems = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb3.setText("COKE = ₱25.00");
        jPanel2.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 40));

        cb1.setText(" PIATOS = ₱22.00");
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        jPanel2.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 40));

        cb2.setText("NOVA = ₱15.00");
        jPanel2.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));

        jLabel1.setText("Qty:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 30, 20));

        jLabel2.setText("Qty:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, 20));
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        jLabel3.setText("Qty:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, 20));
        jPanel2.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 170, 620));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblchange.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblchange.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblchange.setText("Change: ₱0.00 ");
        jPanel5.add(lblchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 40));

        lbltot1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbltot1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltot1.setText("Total: ₱0.00 ");
        jPanel5.add(lbltot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 90));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, 50));

        txtpay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtpay.setEnabled(false);
        jPanel1.add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 180, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Payment: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        btncalc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btncalc.setText("₱");
        btncalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcActionPerformed(evt);
            }
        });
        jPanel1.add(btncalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 60, 80));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 50));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, 50));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 50));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 50));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, 50));

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 70, 50));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 70, 50));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 50));

        jButton21.setText("9");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 70, 50));

        btnx.setText("⌫");
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });
        jPanel1.add(btnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 60, 80));

        btnd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnd.setText(".");
        btnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndActionPerformed(evt);
            }
        });
        jPanel1.add(btnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 70, 50));

        btn0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 50));

        btnitems1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnitems1.setText("Calculate Total Items ");
        btnitems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitems1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnitems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 140, 50));

        btnClearItems.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnClearItems.setText("Clear Items");
        btnClearItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearItemsActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 330, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private String paymentInput = "";
        private double orderTotal = 0;


    
    
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
    paymentInput += "3";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btncalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcActionPerformed
         // TODO add your handling code here:
   try {
        double pay = Double.parseDouble(txtpay.getText());

        if (pay < orderTotal) {
            JOptionPane.showMessageDialog(rootPane, "Insufficient Funds!", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        double change = pay - orderTotal;
        lblchange.setText(String.format("Change: ₱%.2f", change));

    } catch (NumberFormatException e) {
        lblchange.setText("Enter payment first!");
    }


        
    }//GEN-LAST:event_btncalcActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
    paymentInput += "1";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
    paymentInput += "2";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
    paymentInput += "5";
    txtpay.setText(paymentInput);    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
    paymentInput += "4";
    txtpay.setText(paymentInput);    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
    paymentInput += "6";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
    paymentInput += "8";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
    paymentInput += "9";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
    paymentInput += "7";
    txtpay.setText(paymentInput);    }//GEN-LAST:event_btn7ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        // TODO add your handling code here:
           paymentInput = "";
    txtpay.setText("");
    }//GEN-LAST:event_btnxActionPerformed

    private void btndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
            paymentInput += "0";
    txtpay.setText(paymentInput);
    }//GEN-LAST:event_btn0ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        }//GEN-LAST:event_cb1ItemStateChanged

    private void btnitems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitems1ActionPerformed
        // TODO add your handling code here:
            int piaPrice = 22;
    int novaPrice = 15;
    int cokePrice = 25;
    
    orderTotal = 0;

    if (cb1.isSelected()) {
        try 
        {
            String text = txt1.getText().trim();
            int qty1 = text.isEmpty() ? 0 : Integer.parseInt(text);
            
            if (qty1 >= 1) {
                orderTotal += (piaPrice * qty1);
            }
        } 
        catch (NumberFormatException e)
        {
            
        }
    }
    if (cb2.isSelected()) 
    {
        try 
        {
            String text = txt2.getText().trim();
            int qty2 = text.isEmpty() ? 0 : Integer.parseInt(text);
            
            if (qty2 >= 1) {
                orderTotal += (novaPrice * qty2);
            }
        } catch (NumberFormatException e) {
        }
    }
    if (cb3.isSelected())
    {
        try {
            String text = txt3.getText().trim();
            int qty3 = text.isEmpty() ? 0 : Integer.parseInt(text);
            
            if (qty3 >= 1) {
                orderTotal += (cokePrice * qty3); 
            }
        } catch (NumberFormatException e) {
        }
    }

    lbltot1.setText(String.format("Total: ₱%.2f", orderTotal));
    }//GEN-LAST:event_btnitems1ActionPerformed

    private void btnClearItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearItemsActionPerformed
        // TODO add your handling code here:
          // Clear payment
    paymentInput = "";
    txtpay.setText("");

    // Reset total
    orderTotal = 0;

    // Clear quantities
    txt1.setText("0");
    txt2.setText("0");
    txt3.setText("0");

    // Uncheck items
    cb1.setSelected(false);
    cb2.setSelected(false);
    cb3.setSelected(false);

    // Clear displayed totals/change
    lbltot1.setText("Total: ₱0.00");
    lblchange.setText("Change: ₱0.00");
    }//GEN-LAST:event_btnClearItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafe_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClearItems;
    private javax.swing.JButton btncalc;
    private javax.swing.JButton btnd;
    private javax.swing.JButton btnitems1;
    private javax.swing.JButton btnx;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblchange;
    private javax.swing.JLabel lbltot1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txtpay;
    // End of variables declaration//GEN-END:variables
}
